### PR TITLE
allow users to set a city/location for their search

### PR DESCRIPTION
**Pull request by zaclang**
Right now all results are for Prague 😆 . This PR includes a new 'location' command that lets users search for locations and pick one as a base for future searches.
Also implemented some es6 stuff.

### CODE REVIEW

**Review by wzoom — COMMENTED** [review]
This looks awesome. Thanks. I'll try it myself and then merge it.

**Comment by zaclang** [comment]
Cool!

**Comment by wzoom** [comment]
Thanks again for this improvement. I'll do small refactor after the merge, but the functionality should stay the same.

Are you using Lunchy for your team?

**Comment by zaclang** [comment]
Not using it yet, but will soon! Just need to find some time to think about more features :)

**Pull request merged**
